## Monitoria PCD - 19/02

In [1]:
import numpy as np

### Exercício 1)
Utilize comprehension para gerar a lista de todos os números interios entre 0 e 19. Converta a lista em um <font color='blue'>numpy</font> array bidimensional (matriz) com 4 linhas e 5 colunas.

In [2]:
# lista = []
# for i in range(20):
#     lista.append(i)

lista = [i for i in range(20)]

arr = np.array(lista)
print(arr)
print(arr.shape)
print(arr.ndim)

arr2 = arr.reshape(4, 5)
print(arr2)
print(arr2.shape)
print(arr2.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)
1
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
2


In [3]:
# Vamos ver a diferença entre shapes

arr_teste = np.array([i for i in range(20)])
print(arr_teste.shape)
print(arr_teste.ndim)
print(arr_teste)

arr_teste2 = arr_teste.reshape(20, 1)
print(arr_teste2.shape)
print(arr_teste2.ndim)
print(arr_teste2)

arr_teste3 = arr_teste.reshape(1, 20)
print(arr_teste3.shape)
print(arr_teste3.ndim)
print(arr_teste3)

(20,)
1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20, 1)
2
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]
(1, 20)
2
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]


In [5]:
arr_teste = np.array([i for i in range(6)])
print(arr_teste)

arr_teste = arr_teste.reshape(2, 3)
print(arr_teste)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [6]:
formato = arr_teste.shape

print(formato, type(formato))

print('formato[0] guarda linhas:', formato[0])
print('formato[1] guarda colunas:', formato[1])

(2, 3) <class 'tuple'>
formato[0] guarda linhas: 2
formato[1] guarda colunas: 3


- Vetor de tamanho N: shape = (N,) ndim = 1
- Matriz de tamanho N (linhas) por M (colunas): shape = (N,M) ndim = 2

O nome genérico para qualquer numero de dimensoes é Tensor ou no caso do Numpy é Array

### Exercício 2)
Construa um array unidimensional com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. Reformate o array para que se torne uma matriz `A` com 5 linhas e 6 colunas.

In [7]:
arr = np.random.randint(20, size=30)
print(arr)
print(arr.shape)
print(arr.ndim)
print()

A = arr.reshape(5, 6)
print(A)
print(A.shape)
print(A.ndim)

# Atalho
# A = np.random.randint(20, size=(5, 6))

[ 4 14  4  0 17 12 15  5 18 10 12  0  4 16  2  2 15 17 12  4 17 12 14  0
  4 16 11 18  9  5]
(30,)
1

[[ 4 14  4  0 17 12]
 [15  5 18 10 12  0]
 [ 4 16  2  2 15 17]
 [12  4 17 12 14  0]
 [ 4 16 11 18  9  5]]
(5, 6)
2


### Exercício 3)
Crie uma __view__ da matriz `A` gerada na célula anterior contendo:
- as linhas de `A` com índices 0,1 e 3
- as linhas de `A` com índice 1 e 2 e as colunas com índice 0,2 e 4
- as linhas de `A` com índice 1 e 3 e as colunas com índice 1 e 3

In [8]:
A

array([[ 4, 14,  4,  0, 17, 12],
       [15,  5, 18, 10, 12,  0],
       [ 4, 16,  2,  2, 15, 17],
       [12,  4, 17, 12, 14,  0],
       [ 4, 16, 11, 18,  9,  5]])

## A[linhas, colunas]

- A[1, 3] -> Elemento na linha 1 coluna 3
- A[1] ou A[1, :] -> Toda a linha 1
- A[:, 1] -> Toda a coluna 1

#### Seleçao:
- A[[1, 2]] ou A[[1, 2], :] -> Todas as linhas 1 e 2
- A[:, [2, 3]] -> Todas as colunas 2 e 3
- A[[1, 2], [3, 4]] -> Elemento na linha 1 coluna 3 e Elemento na linha 2 coluna 4

#### Slices:
- A[1:4] ou A[1:4, :] -> Linhas de 1 até 4 (1, 2 e 3) com toda a coluna
- A[:, 2:5] -> Colunas de 2 até 5 (2, 3, 4) com toda a linha
- A[1:3, 2:4] -> Linhas de 1 até 3 (1, 2) com coluna de 2 ate 4 (2, 3)

In [9]:
A_l1e3 = A[[1, 3]]
res = A_l1e3[:, [1, 3]]

A[[1, 3]][:, [1, 3]]

array([[ 5, 10],
       [ 4, 12]])

In [10]:
A[1:4, 2:4]

array([[18, 10],
       [ 2,  2],
       [17, 12]])

In [11]:
A[[0, 1, 3]]

array([[ 4, 14,  4,  0, 17, 12],
       [15,  5, 18, 10, 12,  0],
       [12,  4, 17, 12, 14,  0]])

In [12]:
A[1:3, [0, 2, 4]]

array([[15, 18, 12],
       [ 4,  2, 15]])

In [13]:
A[[1,3]][:, [1, 3]]

array([[ 5, 10],
       [ 4, 12]])

In [14]:
A[[1,3], [1, 3]]

array([ 5, 12])

In [15]:
A[0:5:2, 0:5:2]

array([[ 4,  4, 17],
       [ 4,  2, 15],
       [ 4, 11,  9]])