# Numpy Basics

This Jupyter Notebook is part of a series of code resources made available in the repository linked to my Medium publication on the NumPy library. The series is designed to provide readers with practical, in-depth understanding of various NumPy functionalities, an essential library for scientific computing in Python. Here, we explore everything from basic concepts and array manipulation to advanced mathematical operations and broadcasting techniques, offering detailed code examples for each topic covered.

Medium:

Numpy: https://numpy.org/

----

This notebook is dedicated to the fundamentals of NumPy, including array creation, important attributes, and various ways to access and manipulate array elements. We cover essential topics such as:

- Creation of arrays and their basic attributes.
- Accessing elements, including access through loops.
- Slicing techniques for selecting and manipulating subsets of arrays.

This material serves as a solid foundation for those starting with NumPy, providing the necessary knowledge to work efficiently with numeric arrays in Python.


In [1]:
# Installation
#pip install numpy

In [2]:
# Import Numpy
import numpy as np

# Creating arrays

The foundational data structure in NumPy is the array, which operates similarly to Python lists but with notable differences:

- Every element within an array must be of the same type, typically a numerical type such as float or int.
- Arrays enable efficient execution of numerical operations on large volumes of data, outperforming lists in terms of efficiency for these purposes.
- Each dimension of an array is referred to as an axis, with axes numbered starting from 0.

Elements are accessed using square brackets [], similar to Python lists, facilitating intuitive interaction with the array's contents.

In [47]:
# one-dimensional array from a python list
py_list = [1,2,3,4,5]
arr = np.array(py_list)
print("1D array from a python list")
print(py_list, type(py_list))
print(arr, type(arr))

# One-dimensional array with numpy methods
# Creates an array of zeros with 10 elements
arr_1 = np.zeros((10))
print("\n",arr_1)

# Creates an array of ones with 10 elements
arr_2 = np.ones((10))
print("\n",arr_2)

# Creates an array with a sequence of integers from 0 up to, but not including, 10
arr_3 = np.arange(0,10)
print("\n",arr_3)

# Creates an array of 10 evenly spaced values between 1 and 5
arr_4 = np.linspace(start = 1,stop = 5, num = 10)
print("\n",arr_4)

# Creates an array with random methods
arr_5 = np.random.randint(low = 1, high = 20, size = 6)
print("\n",arr_5)

arr_6 = np.random.random(size = 10)
print("\n",arr_6)

1D array from a python list
[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

 [0 1 2 3 4 5 6 7 8 9]

 [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]

 [ 9 14 19  2  9  1]

 [0.03375485 0.09062348 0.06053539 0.99069221 0.89949736 0.76064228
 0.98040449 0.50737763 0.29422618 0.99485766]


In [35]:
# Two-dimensional array (matrix) from a python list
matrix = np.array([[1,2,3],[4,5,6]])
print("Multi-dimensional array - matrix")
print(matrix, type(matrix))

# Two-dimensional array with numpy methods
# Creates an matrix of zeros with 2x3 elements
matrix_1 = np.zeros((2,3))
print("\n",matrix_1)

# Creates an matrix of ones with 3x2 elements
matrix_2 = np.ones((3,2))
print("\n",matrix_2)

# Creates an identity matrix of ones with 4x4 elements
matrix_3 = np.identity(4)
print("\n",matrix_3)

Multi-dimensional array - matrix
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>

 [[0. 0. 0.]
 [0. 0. 0.]]

 [[1. 1.]
 [1. 1.]
 [1. 1.]]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Attributes

Numpy arrays, known as ndarrays, come with a variety of attributes:

- ndarray.ndim indicates the number of axes (dimensions) of the array.
- ndarray.shape is a tuple of integers showing the array's size in each dimension.
- ndarray.size represents the total number of elements within the array.
- ndarray.dtype specifies the type of the elements in the array.
- ndarray.itemsize reveals the size in bytes of each array element.
- ndarray.data is the memory buffer that holds the array's elements.

In [38]:
# Create a 2D numpy array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Number of dimensions of the array
print("Number of dimensions (ndim):", array.ndim)

# Shape of the array
print("Shape of the array:", array.shape)

# Total number of elements in the array
print("Total number of elements (size):", array.size)

# Data type of the array elements
print("Data type of the elements (dtype):", array.dtype)

# Size in bytes of each element in the array
print("Size in bytes of each element (itemsize):", array.itemsize)

Number of dimensions (ndim): 2
Shape of the array: (2, 3)
Total number of elements (size): 6
Data type of the elements (dtype): int32
Size in bytes of each element (itemsize): 4


# Accessing elements

In [40]:
# Create a 2D numpy array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Accessing a specific element [row, column]: 
# Element at 1st row and 2nd column (remember, indexing starts at 0)
print("Element at [1, 2]:", array[1, 2])

# Accessing a specific row
print("First row:", array[0, :])

# Accessing a specific column
print("Second column:", array[:, 1])

# Accessing a range of elements (slicing): 
# Elements from the first row, first to second (exclusive)
print("Slicing, first row, first to second (exclusive):", array[0, 0:2])

# Using negative indexing to access elements from the end: 
# Last element in the last row
print("Element at the end, using negative indexing:", array[-1, -1])

# Accessing elements with step: 
# Every other element from the first row
print("Every other element from the first row:", array[0, ::2])


Element at [1, 2]: 6
First row: [1 2 3]
Second column: [2 5]
Slicing, first row, first to second (exclusive): [1 2]
Element at the end, using negative indexing: 6
Every other element from the first row: [1 3]


# Accessing with loop for

Iterating over an array using a for loop in Python allows you to access each element of the array sequentially. This technique is particularly useful when you need to perform operations on each element of the array or when you want to process the elements in a custom manner.

In [44]:
'''
For a one-dimensional array, iterating with a for loop is straightforward. 
Each iteration of the loop retrieves one element from the array, 
starting from the first element and continuing until 
the last element is reached.
'''

# Creating a one-dimensional numpy array
array_1d = np.array([1, 2, 3, 4])

# Iterating over a one-dimensional array
for element in array_1d:
    print(element)

1
2
3
4


In [45]:
'''
For multi-dimensional arrays, iterating with a for loop accesses 
the array row by row (or along the first axis). 
If you want to access each element individually in a multi-dimensional array,
you can nest for loops - one for each dimension of the array.
'''

# Creating a two-dimensional numpy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Iterating over a two-dimensional array (row by row)
for row in array_2d:
    print("Row:", row)
    # To access individual elements, iterate over each row
    for element in row:
        print(element)

Row: [1 2 3]
1
2
3
Row: [4 5 6]
4
5
6


In [46]:
'''
Numpy also provides functions like nditer() to facilitate efficient iteration 
over arrays of any dimensionality, offering more flexibility and efficiency, 
especially for large and multi-dimensional arrays.
'''
# Efficient iteration over multi-dimensional arrays using nditer()
for element in np.nditer(array_2d):
    print(element)


1
2
3
4
5
6


# Slicing

The most efficient way to traverse an array is through 'slicing', which avoids the use of for loops that are computationally much less efficient.

Array slicing operates similarly to list slicing but extends to multiple dimensions. Omitting an index effectively retrieves the entire dimension that's omitted. Importantly, a slice is a "view" of the original array, similar to a reference, meaning the data is not copied. This approach allows for efficient data manipulation and access without the overhead of duplicating large amounts of data.

In [51]:
# Creating a two-dimensional numpy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing to get the second row
second_row = array_2d[1, :]
print("Second row:", second_row)

# Slicing to get the first column
first_column = array_2d[:, 0]
print("First column:", first_column)

# Slicing to get a sub-array of the first two rows and last two columns
sub_array = array_2d[0:2, 1:3]
print("Sub-array with the first two rows and last two columns:", sub_array)

# Using a step in slicing to get every other element from the last row
every_other = array_2d[-1, ::2]
print("Every other element from the last row:", every_other)

# Demonstrating a slice is a view: Modifying the slice affects the original array
sub_array[0, 0] = 99  # Modify the sub-array
print("Original array after modifying the slice:", array_2d)

Second row: [4 5 6]
First column: [1 4 7]
Sub-array with the first two rows and last two columns: [[2 3]
 [5 6]]
Every other element from the last row: [7 9]
Original array after modifying the slice: [[ 1 99  3]
 [ 4  5  6]
 [ 7  8  9]]
