# Manipulation Methods

This Jupyter Notebook is part of a series of code resources made available in the repository linked to my Medium publication on the NumPy library. The series is designed to provide readers with practical, in-depth understanding of various NumPy functionalities, an essential library for scientific computing in Python. Here, we explore everything from basic concepts and array manipulation to advanced mathematical operations and broadcasting techniques, offering detailed code examples for each topic covered.

Medium:

Numpy: https://numpy.org/

----

This notebook addresses advanced array manipulation methods in NumPy, allowing for sophisticated reorganization and transformation of arrays. We explore methods like:

- reshape, ravel, and flatten for changing the shape or dimensionality of arrays.
- transpose for the transposition of arrays.
- concatenate for combining multiple arrays into a single array.

These methods are fundamental for data manipulation and preparation ahead of more complex analyses or mathematical operations.

In [1]:
import numpy as np

# Reshape

The reshape method allows you to reorganize the array by changing the number of rows and columns. However, the new shape must have the same number of elements as the original array.

In [8]:
# Creating a two-dimensional numpy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d, "\n")

# Using reshape to change the array's shape to 1 row and 9 columns
# This method allows us to reorganize data in the array, maintaining the same number of elements.

reshaped_array = array_2d.reshape((1, 9))
print("Reshaped array (1x9):", reshaped_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Reshaped array (1x9): [[1 2 3 4 5 6 7 8 9]]


# Ravel

The ravel method flattens the array into a one-dimensional array by concatenating its rows. It creates a view of the original array, which means if an element in the raveled array is modified, the original array is also affected.

In [9]:
# Creating a two-dimensional numpy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d, "\n")

# Using ravel to flatten the array into a one-dimensional array
raveled_array = array_2d.ravel()
print("Raveled array:", raveled_array)
# The ravel method creates a one-dimensional view of the array. Changes to this array will affect the original array.

# Demonstrating the view behavior of ravel
raveled_array[0] = 99
print("Original array after modifying the raveled array:", array_2d)
# Since ravel creates a view, the modification is reflected in the original array.

# Resetting the original array for clarity
array_2d[0, 0] = 1


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Raveled array: [1 2 3 4 5 6 7 8 9]
Original array after modifying the raveled array: [[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]


# Flatten

The flatten method also transforms the array into a one-dimensional array by concatenating its rows but, unlike ravel, it creates a copy of the array elements. Consequently, modifications to the flattened array do not affect the original array.

In [10]:
# Creating a two-dimensional numpy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d, "\n")

# Using flatten to flatten the array into a one-dimensional array
flattened_array = array_2d.flatten()
print("Flattened array:", flattened_array)
# Unlike ravel, flatten creates a copy of the array's data. Modifications to this array won't affect the original array.

# Demonstrating the copy behavior of flatten
flattened_array[0] = 99
print("Original array after modifying the flattened array:", array_2d)
# Since flatten creates a copy, the original array remains unchanged after the modification.


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Flattened array: [1 2 3 4 5 6 7 8 9]
Original array after modifying the flattened array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


# Transpose

The transpose method in NumPy is used to permute the dimensions of an array. It reverses or changes the axes of the array according to the values specified. If no values are specified, it defaults to reversing the order of the axes. This is particularly useful in linear algebra, where the transpose of a matrix is a new matrix whose rows are the columns of the original.

The method can be used in several ways, including the numpy.transpose function and the T attribute of an array object. While numpy.transpose allows for the specification of axes to transpose, the T attribute is a simple way to transpose a 2D array (matrix).

In [14]:
# Creating a two-dimensional numpy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d, "\n")

# Using the T attribute to transpose the 2D array
# This switches rows and columns of the array.
transposed_array_T = array_2d.T
print("Transposed array using the T attribute:\n", transposed_array_T)


# Creating a three-dimensional numpy array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n----\n",array_3d, "\n")

# Using numpy.transpose to transpose the 3D array, specifying axes
# This swaps the first two axes of the 3D array.
transposed_array_3d = np.transpose(array_3d, axes=(1, 0, 2))
print("Transposed 3D array with specified axes:\n", transposed_array_3d)

[[1 2 3]
 [4 5 6]] 

Transposed array using the T attribute:
 [[1 4]
 [2 5]
 [3 6]]

----
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 

Transposed 3D array with specified axes:
 [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


# Concatenate


The concatenate method in NumPy is a fundamental tool for combining arrays along a specified axis. This method takes a sequence of arrays and joins them together in the order provided. The arrays must have the same shape, except in the dimension corresponding to the axis along which they are concatenated. For example, to concatenate two matrices (2D arrays) vertically, they must have the same number of columns but can have a different number of rows.

NumPy provides several functions for convenience, such as np.vstack (vertical stack) and np.hstack (horizontal stack), which are specific cases of concatenation along the first and second axes, respectively.

In [20]:
import numpy as np

# Creating two one-dimensional arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concatenating the two arrays
# This joins the arrays end-to-end into a single array.
concatenated_array = np.concatenate((array1, array2))
print("Concatenated 1D arrays:", concatenated_array)


# Creating two two-dimensional arrays
array1_2d = np.array([[1, 2, 3], [4, 5, 6]])
array2_2d = np.array([[10, 11, 12], [13, 14, 15]])

# Vertically stacking the 2D arrays
# This stacks the arrays on top of each other, increasing the number of rows.
vstack_array = np.vstack((array1_2d, array2_2d))
print("Vertically stacked 2D arrays:\n", vstack_array)


# Horizontally stacking arrays
# This places the arrays side by side, increasing the number of columns.
hstack_array = np.hstack((array1_2d, array2_2d))
print("Horizontally stacked arrays:\n", hstack_array)


# Demonstrating concatenation on 2D arrays along a specific axis
# Similar to vstack in this case, combining the arrays vertically.
concatenated_2d = np.concatenate((array1_2d, array2_2d), axis=0)
print("Concatenated 2D arrays along axis 0:\n", concatenated_2d)


Concatenated 1D arrays: [1 2 3 4 5 6]
Vertically stacked 2D arrays:
 [[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [13 14 15]]
Horizontally stacked arrays:
 [[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]]
Concatenated 2D arrays along axis 0:
 [[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [13 14 15]]
