# Mathematical Operations

This Jupyter Notebook is part of a series of code resources made available in the repository linked to my Medium publication on the NumPy library. The series is designed to provide readers with practical, in-depth understanding of various NumPy functionalities, an essential library for scientific computing in Python. Here, we explore everything from basic concepts and array manipulation to advanced mathematical operations and broadcasting techniques, offering detailed code examples for each topic covered.

Medium:

Numpy: https://numpy.org/

----

This notebook explores a wide range of mathematical operations available in NumPy, from trigonometric functions to statistical methods, offering a toolkit for analysis and data processing. We detail:

- Trigonometric functions for manipulation and analysis of geometric or periodic data.
- Sum and product operations for aggregate calculations.
- Square root, exponentials, and logarithms for mathematical transformations.
- Statistical methods and comparison functions for data analysis.

This content is essential for those looking to use NumPy for advanced mathematics and data science tasks.

In [1]:
import numpy as np

# Trigonometric functions


NumPy provides a comprehensive set of trigonometric functions that allow for the efficient computation of cosine, sine, tangent, and other trigonometric operations on arrays. These functions are vectorized, meaning they can be applied element-wise to arrays, making it straightforward to perform complex trigonometric calculations on large datasets.

The trigonometric functions in NumPy include but are not limited to `np.sin()` for calculating the sine, `np.cos()` for the cosine, and `np.tan()` for the tangent of angles provided in radians. In addition to these basic trigonometric functions, NumPy offers functions for hyperbolic trigonometry, such as `np.sinh()`, `np.cosh()`, and `np.tanh()`, as well as functions to convert degrees to radians (`np.deg2rad()`) and radians to degrees (`np.rad2deg()`), facilitating the transition between different units of angle measurement.

In [5]:
# Creating an array of angles in degrees
angles_degrees = np.array([0, 30, 45, 60, 90])
print("Angles degrees: ",angles_degrees)

# Converting angles to radians since trigonometric functions expect angles in radians
angles_radians = np.deg2rad(angles_degrees)
print("\nAngles radians: ",angles_radians)

# Calculating sine of each angle
sine_values = np.sin(angles_radians)
print("\nSine values of angles:", sine_values)

# Calculating cosine of each angle
cosine_values = np.cos(angles_radians)
print("\nCosine values of angles:", cosine_values)

# Calculating tangent of each angle
tangent_values = np.tan(angles_radians)
print("\nTangent values of angles:", tangent_values)

# Demonstrating inverse trigonometric functions by calculating the arc sine (inverse of sine)
# This returns the angles in radians, so let's convert it back to degrees for readability
arc_sine_degrees = np.rad2deg(np.arcsin(sine_values))
print("\nArcsine (in degrees) of sine values:", arc_sine_degrees)

# Demonstrating hyperbolic sine function on the radians array
sinh_values = np.sinh(angles_radians)
print("\nHyperbolic sine values of angles:", sinh_values)


Angles degrees:  [ 0 30 45 60 90]

Angles radians:  [0.         0.52359878 0.78539816 1.04719755 1.57079633]

Sine values of angles: [0.         0.5        0.70710678 0.8660254  1.        ]

Cosine values of angles: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]

Tangent values of angles: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]

Arcsine (in degrees) of sine values: [ 0. 30. 45. 60. 90.]

Hyperbolic sine values of angles: [0.         0.54785347 0.86867096 1.24936705 2.3012989 ]


# Sum and product

NumPy provides efficient functions for calculating the sum and product of array elements: `np.sum` and `np.prod`, respectively. These functions are highly versatile, allowing for the computation of the total sum or product over the entire array or along a specified axis. This flexibility makes it easy to perform column-wise or row-wise aggregations on multi-dimensional arrays, an essential operation in many data processing tasks.

- `np.sum`: Calculates the sum of array elements. You can specify the axis (e.g., 0 for columns, 1 for rows in a 2D array) to perform the summation across. Without specifying the axis, it sums up all elements in the array.
- `np.prod`: Computes the product of array elements. Similar to np.sum, you can determine the axis along which to calculate the product, or omit the axis parameter to compute the product of all elements in the array.

In [8]:
# Creating a two-dimensional numpy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)

# Calculating the sum of all elements in the array
total_sum = np.sum(array_2d)
print("\nTotal sum of all elements:", total_sum)

# Calculating the sum along the columns (axis 0)
sum_columns = np.sum(array_2d, axis=0)
print("\nSum of elements along columns:", sum_columns)

# Calculating the sum along the rows (axis 1)
sum_rows = np.sum(array_2d, axis=1)
print("\nSum of elements along rows:", sum_rows)

# Calculating the product of all elements in the array
total_product = np.prod(array_2d)
print("\nTotal product of all elements:", total_product)

# Calculating the product along the columns (axis 0)
product_columns = np.prod(array_2d, axis=0)
print("\nProduct of elements along columns:", product_columns)

# Calculating the product along the rows (axis 1)
product_rows = np.prod(array_2d, axis=1)
print("\nProduct of elements along rows:", product_rows)


[[1 2 3]
 [4 5 6]]

Total sum of all elements: 21

Sum of elements along columns: [5 7 9]

Sum of elements along rows: [ 6 15]

Total product of all elements: 720

Product of elements along columns: [ 4 10 18]

Product of elements along rows: [  6 120]


# Square root


The square root function in NumPy, `np.sqrt`, computes the square root of each element in an array. This function is essential for various mathematical computations, especially in scientific and engineering applications where calculating the magnitude of vectors, distances between points, or applying certain mathematical formulas requires square roots.

NumPy's `np.sqrt` function is vectorized, meaning it can perform the square root operation on each element of an array individually and efficiently, without the need for explicit loops.

In [10]:
# Creating a one-dimensional numpy array of positive numbers
array_1d = np.array([1, 4, 9, 16, 25])
print(array_1d)

# Calculating the square root of each element in the array
sqrt_array = np.sqrt(array_1d)
print("\nSquare root of each element:", sqrt_array)

# Creating a two-dimensional numpy array
array_2d = np.array([[1, 2, 3], [4, 9, 16]])
print("\n", array_2d)

# Calculating the square root of each element in the 2D array
sqrt_array_2d = np.sqrt(array_2d)
print("\nSquare root of each element in the 2D array:\n", sqrt_array_2d)

# Demonstrating the square root of a complex number array
complex_array = np.array([1+4j, 16+9j])
print("\n", complex_array)

sqrt_complex_array = np.sqrt(complex_array)
print("\nSquare root of complex numbers:", sqrt_complex_array)

[ 1  4  9 16 25]

Square root of each element: [1. 2. 3. 4. 5.]

 [[ 1  2  3]
 [ 4  9 16]]

Square root of each element in the 2D array:
 [[1.         1.41421356 1.73205081]
 [2.         3.         4.        ]]

 [ 1.+4.j 16.+9.j]

Square root of complex numbers: [1.60048518+1.24962107j 4.14472917+1.0857163j ]


# Exponents and logarithms

NumPy provides a comprehensive set of functions for computing exponents and logarithms, catering to a wide range of mathematical and scientific computing needs. These functions allow for efficient and element-wise operations on arrays, making it straightforward to perform complex calculations on large datasets.

In [11]:
# Creating a one-dimensional numpy array
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)

# Computing the exponential of each element
exp_array = np.exp(array_1d)
print("\nExponential of each element:", exp_array)


# Computing the exponential with base 2
exp2_array = np.exp2(array_1d)
print("\nBase-2 exponential of each element:", exp2_array)


# Computing the natural logarithm of each element
log_array = np.log(array_1d)
print("\nNatural logarithm of each element:", log_array)


# Computing the base-2 logarithm of each element
log2_array = np.log2(array_1d)
print("\nBase-2 logarithm of each element:", log2_array)


# Computing the base-10 logarithm of each element
log10_array = np.log10(array_1d)
print("\nBase-10 logarithm of each element:", log10_array)


[1 2 3 4 5]

Exponential of each element: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

Base-2 exponential of each element: [ 2.  4.  8. 16. 32.]

Natural logarithm of each element: [0.         0.69314718 1.09861229 1.38629436 1.60943791]

Base-2 logarithm of each element: [0.         1.         1.5849625  2.         2.32192809]

Base-10 logarithm of each element: [0.         0.30103    0.47712125 0.60205999 0.69897   ]


# Statistical methods
NumPy offers a wide array of statistical methods that allow for the analysis and processing of data arrays. These methods include functions for calculating measures of central tendency (like mean and median), dispersion (such as standard deviation and variance), and other statistical properties (including min, max, sum, and more). Utilizing these functions helps in understanding the distribution, variability, and overall characteristics of the data.

In [12]:
# Creating a one-dimensional numpy array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array_1d)

# Calculating the mean of the array
mean_value = np.mean(array_1d)
print("\nMean of the data:", mean_value)

# Calculating the median of the array
median_value = np.median(array_1d)
print("\nMedian of the data:", median_value)

# Calculating the standard deviation of the array
std_deviation = np.std(array_1d)
print("\nStandard deviation of the data:", std_deviation)

# Calculating the variance of the array
variance = np.var(array_1d)
print("\nVariance of the data:", variance)

# Finding the minimum value in the array
min_value = np.min(array_1d)
print("\nMinimum value of the data:", min_value)

# Finding the maximum value in the array
max_value = np.max(array_1d)
print("\nMaximum value of the data:", max_value)

# Summing all elements in the array
total_sum = np.sum(array_1d)
print("\nSum of all elements in the data:", total_sum)


[1 2 3 4 5 6 7 8 9]

Mean of the data: 5.0

Median of the data: 5.0

Standard deviation of the data: 2.581988897471611

Variance of the data: 6.666666666666667

Minimum value of the data: 1

Maximum value of the data: 9

Sum of all elements in the data: 45


# Comparison methods

NumPy provides a suite of comparison methods that allow for element-wise comparison between arrays or between arrays and scalars. These methods are crucial for data analysis, filtering, and conditional operations, enabling users to efficiently identify and act upon specific conditions within datasets.

Key comparison functions include:

- `np.equal` (or ==): Checks if elements are equal.
- `np.not_equal` (or !=): Checks if elements are not equal.
- `np.greater` (or >): Checks if elements of the first array are greater than the second array.
- `np.greater_equal` (or >=): Checks if elements of the first array are greater than or equal to the second array.
- `np.less` (or <): Checks if elements of the first array are less than those of the second.
- `np.less_equal` (or <=): Checks if elements of the first array are less than or equal to the second array.

In [14]:
# Creating two one-dimensional numpy arrays for comparison
array1 = np.array([1, 3, 5, 7])
array2 = np.array([2, 3, 4, 7])

# Checking if elements are equal
are_equal = np.equal(array1, array2)
print("Elements equal:", are_equal)

# Checking if elements are not equal
not_equal = np.not_equal(array1, array2)
print("Elements not equal:", not_equal)

# Checking if elements of the first array are greater than the second
greater_than = np.greater(array1, array2)
print("Elements of array1 greater than array2:", greater_than)

# Checking if elements of array1 are less than those of array2
less_than = np.less(array1, array2)
print("Elements of array1 less than array2:", less_than)

Elements equal: [False  True False  True]
Elements not equal: [ True False  True False]
Elements of array1 greater than array2: [False False  True False]
Elements of array1 less than array2: [ True False False False]
