# Broadcasting and Matrix Operations

This Jupyter Notebook is part of a series of code resources made available in the repository linked to my Medium publication on the NumPy library. The series is designed to provide readers with practical, in-depth understanding of various NumPy functionalities, an essential library for scientific computing in Python. Here, we explore everything from basic concepts and array manipulation to advanced mathematical operations and broadcasting techniques, offering detailed code examples for each topic covered.

Medium:

Numpy: https://numpy.org/

----

This notebook focuses on two advanced areas of NumPy: broadcasting and matrix operations. Broadcasting allows for arithmetic operations between arrays of different sizes, while matrix operations cover essential calculations in linear algebra. We discuss:

- Broadcasting with arrays and scalars, and between arrays, facilitating complex calculations without the need for explicit loops.
- Matrix and vector operations, including matrix multiplication, dot products, and vector operations, crucial for scientific computations and engineering.

These advanced topics demonstrate NumPy's power for data manipulation and complex mathematical calculations, serving as a valuable reference for scientific and data analysis applications.

In [1]:
import numpy as np

# Broadcasting
To ensure computational efficiency in performing operations between arrays, NumPy employs an array extension mechanism known as "broadcasting." Through broadcasting:

Arithmetic operations on arrays (such as addition, subtraction, multiplication, and division) are conducted on an element-wise basis.
Broadcasting manipulates the dimensions of the arrays involved in arithmetic operations so that they match, thereby enabling these operations to be carried out on an element-wise basis.

# Broadcasting and operations between an array and a scalar
Broadcasting in NumPy is a powerful concept that allows for array operations between arrays of different shapes. It enables you to perform arithmetic operations on arrays without the need for explicitly matching their sizes. This feature is particularly useful for performing operations between an array and a scalar value.

When performing operations between an array and a scalar, broadcasting automatically extends the scalar to match the shape of the array. This means that the scalar value is conceptually replicated to match the dimensions of the array, and then the operation is carried out element-wise. This allows for efficient and intuitive computations without manually resizing or replicating the scalar value across the array.

In [2]:
# Creating a one-dimensional numpy array
array = np.array([1, 2, 3, 4, 5])
print(array)

# Adding a scalar to the array
add_scalar = array + 10
print("\nAdding a scalar 10 to the array:", add_scalar)

# Multiplying the array by a scalar
multiply_scalar = array * 2
print("\nMultiplying the array by a scalar 2:", multiply_scalar)

# Subtracting a scalar from the array
subtract_scalar = array - 5
print("\nSubtracting a scalar 5 from the array:", subtract_scalar)

# Dividing the array by a scalar
divide_scalar = array / 2
print("\nDividing the array by a scalar 2:", divide_scalar)

[1 2 3 4 5]

Adding a scalar 10 to the array: [11 12 13 14 15]

Multiplying the array by a scalar 2: [ 2  4  6  8 10]

Subtracting a scalar 5 from the array: [-4 -3 -2 -1  0]

Dividing the array by a scalar 2: [0.5 1.  1.5 2.  2.5]


# Broadcasting and operations between arrays
Broadcasting in NumPy is a technique that allows operations to be performed on arrays of different shapes. It automatically adjusts the shapes of arrays without explicitly resizing them, enabling you to perform arithmetic operations between arrays that wouldn't normally be compatible due to their different dimensions.

For broadcasting to occur between two arrays, NumPy follows these rules:

- If the arrays don't have the same number of dimensions, the shape of the smaller array is "padded" with ones on its leading (left) side.
- If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
- If in any dimension the sizes disagree and neither is equal to 1, a broadcasting error is raised.

In [3]:
# Creating a two-dimensional numpy array (3x3)
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array2d)

# Creating a one-dimensional numpy array
array1d = np.array([1, 0, 1])
print("\n",array1d)

# Adding a 1D array to a 2D array
add_arrays = array2d + array1d
print("\nAdding 1D array to each row of 2D array:\n", add_arrays)

# Creating another 1D array for column-wise operation
array1d_col = np.array([[1], [2], [3]])

# Adding the column array to the 2D array
add_columns = array2d + array1d_col
print("\nAdding 1D column array to each column of 2D array:\n", add_columns)

# Multiplying a 2D array by a scalar using broadcasting
multiply_scalar = array2d * 2
print("\nMultiplying 2D array by a scalar 2:\n", multiply_scalar)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [1 0 1]

Adding 1D array to each row of 2D array:
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]

Adding 1D column array to each column of 2D array:
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]

Multiplying 2D array by a scalar 2:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Broadcasting is also used in assignments

In [5]:
# Creating a two-dimensional numpy array (5x3)
array2d = np.zeros((5,3))
print(array2d)

array2d[:3] = [-1,-2,-3]
print("\n",array2d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [[-1. -2. -3.]
 [-1. -2. -3.]
 [-1. -2. -3.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


# Matrix and vector operations
NumPy provides extensive support for matrix and vector operations, essential for linear algebra and many scientific computations. These operations include matrix multiplication, dot products, cross products, and more. Vector operations are operations applied on arrays that represent vectors in a mathematical sense.

- Matrix Multiplication: Performed using the `@` operator or the `np.dot` function. It computes the dot product of two arrays. For 2D arrays, it is equivalent to matrix multiplication.
- Dot Product: Calculated using `np.dot`. It represents the sum of the products of the corresponding entries of two sequences of numbers. It's a critical operation in many algorithms.
- Cross Product: Computed with `np.cross`. This operation finds the vector perpendicular to two vectors in three-dimensional space, useful in physics and engineering.
- Vector Norm: Calculated with `np.linalg.norm`. It measures the magnitude of a vector, essential in normalizing vectors or measuring distances

In [8]:
# Defining two 2D arrays (matrices)
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(matrix1)
print("\n", matrix2)

# Matrix multiplication
matrix_product = matrix1 @ matrix2
print("\nMatrix multiplication result:\n", matrix_product)

# Dot product of two vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
print("\n Vectors")
print("\n", vector1)
print("\n", vector2)

dot_product = np.dot(vector1, vector2)
print("\nDot product of two vectors:", dot_product)

# Cross product of two vectors
cross_product = np.cross(vector1, vector2)
print("\nCross product of two vectors:", cross_product)

# Calculating the norm (magnitude) of a vector
vector_norm = np.linalg.norm(vector1)
print("\nNorm of the vector:", vector_norm)

[[1 2]
 [3 4]]

 [[5 6]
 [7 8]]

Matrix multiplication result:
 [[19 22]
 [43 50]]

 Vectors

 [1 2 3]

 [4 5 6]

Dot product of two vectors: 32

Cross product of two vectors: [-3  6 -3]

Norm of the vector: 3.7416573867739413
