# <span style="color:blue"> MBA em Ciência de Dados</span>
# <span style="color:blue">Programação para Ciência de Dados</span>

## <span style="color:blue">Numpy Parte I - Exercícios</span>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**

#### <span style="color:red">Recomenda-se fortemente que os exercícios sejam feitos sem consultar as respostas antecipadamente.</span>

In [ ]:
import numpy as np

### Exercício 1)
Utilize comprehension para gerar a lista de todos os números interios entre 0 e 19. Converta a lista em um <font color='blue'>numpy</font> array bidimensional (matriz) com 4 linhas e 5 colunas.

In [164]:
l = [i for i in range(20)]
A = np.array(l).reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### Exercício 2)
Construa um array unidimensional com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. Reformate o array para que se torne uma matriz `A` com 5 linhas e 6 colunas.

In [165]:
A = np.random.randint(0,20,30).reshape(5,6)
A

array([[ 9, 15, 14, 14, 18, 11],
       [19,  2,  4, 18,  6,  8],
       [ 6, 17,  3, 13, 17,  8],
       [ 1, 19, 14,  6, 11,  7],
       [14,  2, 13, 16,  3, 17]])

### Exercício 3)
Crie uma __view__ da matriz `A` gerada na célula anterior contendo:
- as linhas de `A` com índices 0,1 e 3
- as linhas de `A` com índice 1 e 2 e as colunas com índice 0,2 e 4
- as linhas de `A` com índice 1 e 3 e as colunas com índice 1 e 3

In [166]:
A[[0,1,3]] # linhas de `A` com índices 0,1 e 3

array([[ 9, 15, 14, 14, 18, 11],
       [19,  2,  4, 18,  6,  8],
       [ 1, 19, 14,  6, 11,  7]])

In [167]:
A[1:3,[0,2,4]] # linhas de `A` com índice 1 e 2 e as colunas com índice 0,2 e 4

array([[19,  4,  6],
       [ 6,  3, 17]])

In [168]:
A[[1,3]][:,[1,3]] #linhas de `A` com índice 1 e 3 e as colunas com índice 1 e 3

array([[ 2, 18],
       [19,  6]])

### Exercício 4)
Construa um array `A` bidimensional 5x6 com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20.
- faça uma cópia do array `A` criado, chamando a cópia de `Ac`
- Substitua todos os elementos do array `A` que sejam maiores que 10 pelo valor -1
- Substitua todos os elementos do array `Ac` que sejam maiores que 7 e menores que 15 pelo valor -1

__Dica:__ Gere máscaras booleanas para realizar as modificações nos arrays.

In [61]:
import numpy as np

np.random.seed(42)

A = np.random.randint(low=0, high=20, size=30)
A = A.reshape(5,6)
A

array([[ 6, 19, 14, 10,  7,  6],
       [18, 10, 10,  3,  7,  2],
       [ 1, 11,  5,  1,  0, 11],
       [11, 16,  9, 15, 14, 14],
       [18, 11, 19,  2,  4, 18]])

In [62]:
Ac = A.copy()
Ac

array([[ 6, 19, 14, 10,  7,  6],
       [18, 10, 10,  3,  7,  2],
       [ 1, 11,  5,  1,  0, 11],
       [11, 16,  9, 15, 14, 14],
       [18, 11, 19,  2,  4, 18]])

In [18]:
mask = A > 10
mask

array([[False,  True,  True, False, False, False],
       [ True, False, False, False, False, False],
       [False,  True, False, False, False,  True],
       [ True,  True, False,  True,  True,  True],
       [ True,  True,  True, False, False,  True]])

In [19]:
A[mask]

array([19, 14, 18, 11, 11, 11, 16, 15, 14, 14, 18, 11, 19, 18])

In [20]:
A[mask] = -1
A

array([[ 6, -1, -1, 10,  7,  6],
       [-1, 10, 10,  3,  7,  2],
       [ 1, -1,  5,  1,  0, -1],
       [-1, -1,  9, -1, -1, -1],
       [-1, -1, -1,  2,  4, -1]])

In [21]:
Ac

array([[ 6, 19, 14, 10,  7,  6],
       [18, 10, 10,  3,  7,  2],
       [ 1, 11,  5,  1,  0, 11],
       [11, 16,  9, 15, 14, 14],
       [18, 11, 19,  2,  4, 18]])

In [63]:
m = Ac > 0
Ac[m].size > 0

True

In [64]:
Ac

array([[ 6, 19, 14, 10,  7,  6],
       [18, 10, 10,  3,  7,  2],
       [ 1, 11,  5,  1,  0, 11],
       [11, 16,  9, 15, 14, 14],
       [18, 11, 19,  2,  4, 18]])

In [67]:
(Ac >= 0).all()

True

In [68]:
(Ac >= 0).any()

True

In [ ]:
f = lambda x: x > 7
maskac = (f(Ac)) & (Ac < 15)
maskac

In [70]:
maskac = (Ac > 7) & (Ac < 15)
maskac

array([[False, False,  True,  True, False, False],
       [False,  True,  True, False, False, False],
       [False,  True, False, False, False,  True],
       [ True, False,  True, False,  True,  True],
       [False,  True, False, False, False, False]])

In [71]:
Ac[maskac] = -1
Ac

array([[ 6, 19, -1, -1,  7,  6],
       [18, -1, -1,  3,  7,  2],
       [ 1, -1,  5,  1,  0, -1],
       [-1, 16, -1, 15, -1, -1],
       [18, -1, 19,  2,  4, 18]])

In [72]:
print(True & True)
print(False & True)
print(True & False)
print(False & False)

True
False
False
False


### Exercício 5)
Construa um array `A` com 20 linhas e 10 colunas onde os elementos são os números interios de  1 até 200.
- Crie uma __view__ de `A` chamada `A_lpares` contendo apenas as linhas de `A` com índice par.
- Crie uma __view__ de `A` chamada `A_lpares_cimpares` contendo as linhas `A` com índice par e colunas com índice ímpar.

In [84]:
max = 200
l = 20
c = 10
A = np.arange(1, max + 1).reshape(l, c)
A

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160],
       [161, 162, 163, 164, 165, 166, 167, 168, 169, 170

In [90]:
maskl = np.arange(0, l, 2)
# maskl = np.arange(start=0, stop=l, step=2)
A_lpares = A[maskl, :]
A_lpares

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [161, 162, 163, 164, 165, 166, 167, 168, 169, 170],
       [181, 182, 183, 184, 185, 186, 187, 188, 189, 190]])

In [99]:
masklp = np.arange(0, l, 2)
masklp

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [100]:
maskci = np.arange(1, c, 2)
maskci

array([1, 3, 5, 7, 9])

In [101]:
A[masklp][:, maskci]

array([[  2,   4,   6,   8,  10],
       [ 22,  24,  26,  28,  30],
       [ 42,  44,  46,  48,  50],
       [ 62,  64,  66,  68,  70],
       [ 82,  84,  86,  88,  90],
       [102, 104, 106, 108, 110],
       [122, 124, 126, 128, 130],
       [142, 144, 146, 148, 150],
       [162, 164, 166, 168, 170],
       [182, 184, 186, 188, 190]])

In [104]:
A[masklp][:, maskci]

array([[  2,   4,   6,   8,  10],
       [ 22,  24,  26,  28,  30],
       [ 42,  44,  46,  48,  50],
       [ 62,  64,  66,  68,  70],
       [ 82,  84,  86,  88,  90],
       [102, 104, 106, 108, 110],
       [122, 124, 126, 128, 130],
       [142, 144, 146, 148, 150],
       [162, 164, 166, 168, 170],
       [182, 184, 186, 188, 190]])

In [107]:
A[masklp, :][:, maskci]

array([[  2,   4,   6,   8,  10],
       [ 22,  24,  26,  28,  30],
       [ 42,  44,  46,  48,  50],
       [ 62,  64,  66,  68,  70],
       [ 82,  84,  86,  88,  90],
       [102, 104, 106, 108, 110],
       [122, 124, 126, 128, 130],
       [142, 144, 146, 148, 150],
       [162, 164, 166, 168, 170],
       [182, 184, 186, 188, 190]])

### Exercício 6)
Substitua os elememtos do array `A` do exercício anterior por -1 quando pelo menos um dos índices do elemento é par.

__Dica:__ Construa uma máscara booleana

In [110]:
print(True or True)
print(False or True)
print(True or False)
print(False or False)

True
True
True
False


In [111]:
print(True | True)
print(False | True)
print(True | False)
print(False | False)

True
True
True
False


In [113]:
max = 200
l = 20
c = 10
A = np.arange(1, max + 1).reshape(l, c)
A

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160],
       [161, 162, 163, 164, 165, 166, 167, 168, 169, 170

In [115]:
3 % 2

1

In [119]:
i = 2
j = 1
i%2==0 or j%2==0

True

In [114]:
for i in range(A.shape[0]):
  for j in range(A.shape[1]):
    if i%2==0 or j%2==0:
      A[i, j] = -1

A

array([[ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  12,  -1,  14,  -1,  16,  -1,  18,  -1,  20],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  32,  -1,  34,  -1,  36,  -1,  38,  -1,  40],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  52,  -1,  54,  -1,  56,  -1,  58,  -1,  60],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  72,  -1,  74,  -1,  76,  -1,  78,  -1,  80],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  92,  -1,  94,  -1,  96,  -1,  98,  -1, 100],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1, 112,  -1, 114,  -1, 116,  -1, 118,  -1, 120],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1, 132,  -1, 134,  -1, 136,  -1, 138,  -1, 140],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1, 152,  -1, 154,  -1, 156,  -1, 158,  -1, 160],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1

In [130]:
mask = [i%2==0 or j%2==0 for i in range(A.shape[0]) for j in range(A.shape[1])]
mask = np.array(mask).reshape(A.shape[0], A.shape[1])
A[mask] = -1
A

array([[ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  12,  -1,  14,  -1,  16,  -1,  18,  -1,  20],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  32,  -1,  34,  -1,  36,  -1,  38,  -1,  40],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  52,  -1,  54,  -1,  56,  -1,  58,  -1,  60],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  72,  -1,  74,  -1,  76,  -1,  78,  -1,  80],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  92,  -1,  94,  -1,  96,  -1,  98,  -1, 100],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1, 112,  -1, 114,  -1, 116,  -1, 118,  -1, 120],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1, 132,  -1, 134,  -1, 136,  -1, 138,  -1, 140],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1, 152,  -1, 154,  -1, 156,  -1, 158,  -1, 160],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1

### Exercício 7)
Considere o array `X` de números tipo <font color='blue'>float</font> gerado a partir de uma distribuição uniforme no intervalo entre 0 e 1. Escreva um código para encontrar os três menores valores do array.

__Dica:__ Converta o array em uma lista e ordene.

In [160]:
np.random.seed(42)

X = np.random.uniform(0,1,20)
X

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258,
       0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
       0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914])

In [161]:
Y = X.copy()
Y.sort()
Y

array([0.02058449, 0.05808361, 0.15599452, 0.15601864, 0.18182497,
       0.18340451, 0.21233911, 0.29122914, 0.30424224, 0.37454012,
       0.43194502, 0.52475643, 0.59865848, 0.60111501, 0.70807258,
       0.73199394, 0.83244264, 0.86617615, 0.95071431, 0.96990985])

In [162]:
X

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258,
       0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
       0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914])

In [135]:
result = sorted(X)[0:3]
result

[0.020584494295802447, 0.05808361216819946, 0.15599452033620265]

In [136]:
sorted(X)[-3:]

[0.8661761457749352, 0.9507143064099162, 0.9699098521619943]

In [152]:
type(sorted(X))

list

In [153]:
type(X)

numpy.ndarray

In [154]:
x = np.array(sorted(X))
x[0]
x[[-3, -2, -1]]

array([0.86617615, 0.95071431, 0.96990985])

### Exercício 8)
Escreva uma função chamada `troca_colunas` que recebe um array e o índice de duas colunas como parâmetros e retorna o array com as colunas trocadas. Por exemplo:
```python
X = np.array([[0, 1, 2, 3, 4, 5],
              [0, 1, 2, 3, 4, 5],
              [0, 1, 2, 3, 4, 5]])

X = troca_colunas(X,1,3)
print(X)
```
deve resultar em
```python
[[0 3 2 1 4 5]
 [0 3 2 1 4 5]
 [0 3 2 1 4 5]]
```


In [163]:
def troca_colunas(A,i,j):
    ci = A[:, i].copy()
    cj = A[:, j].copy()
    A[:, i] = cj
    A[:, j] = ci
    return(A)

X = np.array([[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]])
print(X)

X = troca_colunas(X,1,3)
print(X)

[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]
[[0 3 2 1 4 5]
 [0 3 2 1 4 5]
 [0 3 2 1 4 5]]


### Exercício 9)
Os métodos <font color='blue'>vstack</font> e <font color='blue'>hstack</font> do <font color='blue'>numpy</font> empilha matrizes na vertical e horizontal, respectivamente. Por exemplo:
```python
A = [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
B = [[2.0, 2.0, 2.0], [2.0, 2.0, 2.0]]

C = np.vstack((A,B))
print(C)
```
resulta em
```python
[[1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]
```
Escreva um código para gerar duas matrizes `A` e `B` de números inteiros randômicos no intervalo entre 0 e 10, onde:
- A matriz `A` é 5x6
- A matriz `B` é 5x3

Utilize o método <font color='blue'>hstack</font> para empilhar as matrizes

O que acontece se tentar utilizar o método <font color='blue'>vstack</font>? Explique o motivo da mensagem gerada.

In [174]:
A = np.random.randint(0,10,30).reshape(5,6)
A

array([[0, 2, 4, 2, 0, 4],
       [9, 6, 6, 8, 9, 9],
       [2, 6, 0, 3, 3, 4],
       [6, 6, 3, 6, 2, 5],
       [1, 9, 8, 4, 5, 3]])

In [175]:
B = -1*np.random.randint(0,10,15).reshape(5,3)
B

array([[-9, -6, -8],
       [-6,  0,  0],
       [-8, -8, -3],
       [-8, -2, -6],
       [-5, -7, -8]])

In [176]:
C = np.hstack((A,B))
C


array([[ 0,  2,  4,  2,  0,  4, -9, -6, -8],
       [ 9,  6,  6,  8,  9,  9, -6,  0,  0],
       [ 2,  6,  0,  3,  3,  4, -8, -8, -3],
       [ 6,  6,  3,  6,  2,  5, -8, -2, -6],
       [ 1,  9,  8,  4,  5,  3, -5, -7, -8]])

In [178]:
# all the input array dimensions except for the concatenation axis must match
# exactly, but along dimension 1, the array at index 0 has size 6 and the array
# at index 1 has size 3

# D = np.vstack((A,B))
# D


In [180]:
E = np.vstack((A,A))
E


array([[0, 2, 4, 2, 0, 4],
       [9, 6, 6, 8, 9, 9],
       [2, 6, 0, 3, 3, 4],
       [6, 6, 3, 6, 2, 5],
       [1, 9, 8, 4, 5, 3],
       [0, 2, 4, 2, 0, 4],
       [9, 6, 6, 8, 9, 9],
       [2, 6, 0, 3, 3, 4],
       [6, 6, 3, 6, 2, 5],
       [1, 9, 8, 4, 5, 3]])

### Exercício 10)
Escreva um código para, data uma matriz, zerar todos os elementos abaixo da diagonal principal da matriz. Por exemplo:
```python
[[2 8 3 4 8]
 [4 8 7 7 3]
 [8 2 3 1 4]
 [8 6 3 8 1]
 [6 4 4 6 1]]
```
deve resultar em
```python
[[2 8 3 4 8]
 [0 8 7 7 3]
 [0 0 3 1 4]
 [0 0 0 8 1]
 [0 0 0 0 1]]
```

In [169]:
A = np.random.randint(1,10,25).reshape(5,5)
A

array([[8, 4, 2, 6, 6],
       [4, 6, 2, 2, 4],
       [8, 7, 9, 8, 5],
       [2, 5, 8, 9, 9],
       [1, 9, 7, 9, 8]])

In [170]:
mask = [True if i>j else False for i in range(A.shape[0]) for j in range(A.shape[1])]
mask = np.array(mask).reshape(A.shape[0],A.shape[1])
mask

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True,  True, False]])

In [171]:
A[mask] = 0
A


array([[8, 4, 2, 6, 6],
       [0, 6, 2, 2, 4],
       [0, 0, 9, 8, 5],
       [0, 0, 0, 9, 9],
       [0, 0, 0, 0, 8]])

In [172]:
# usando o método 'triu' do numpy
A = np.random.randint(1,10,25).reshape(5,5)
A

array([[1, 8, 8, 3, 1],
       [8, 3, 3, 1, 5],
       [7, 9, 7, 9, 8],
       [2, 1, 7, 7, 8],
       [5, 3, 8, 6, 3]])

In [173]:
A = np.triu(A)
A

array([[1, 8, 8, 3, 1],
       [0, 3, 3, 1, 5],
       [0, 0, 7, 9, 8],
       [0, 0, 0, 7, 8],
       [0, 0, 0, 0, 3]])