# Revisão Numpy

## Comandos Básicos

In [2]:
import numpy as np

In [10]:
# Criar array 1d
a = [1,3,5,7,9,10]
b1d = np.array(a)
b1d

array([ 1,  3,  5,  7,  9, 10])

In [11]:
# Criar array 2d
a = [[1,3,5],[7,9,10]]
b2d = np.array(a)
b2d

array([[ 1,  3,  5],
       [ 7,  9, 10]])

In [7]:
# retorna array de zeros
np.zeros(shape=(5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
# retorna array de uns
np.ones(shape=(5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# retorna um array com dados espaçados
np.arange(start=1, stop=10, step=2)

array([1, 3, 5, 7, 9])

In [42]:
# retorna array espaçado em um intervalo fixo
np.linspace(start=1, stop=10, num=100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [13]:
# acessa dimensão
b1d.ndim

1

In [14]:
# acessa dimensão
b2d.ndim

2

In [17]:
# tamanho do array em cada dimensão
b1d.shape

(6,)

In [16]:
# tamanho do array em cada dimensão
b2d.shape

(2, 3)

In [18]:
# numero total de elementos
b1d.size

6

In [43]:
len(b1d)

6

In [48]:
b2d[:]

array([[ 1,  3,  5],
       [ 7,  9, 10]])

In [50]:
len(b2d[1])

3

In [19]:
# tipos dos elementos
b1d.dtype

dtype('int64')

In [20]:
# tamanho em byte de cada elemento
b1d.itemsize

8

In [51]:
b1d.itemsize * b1d.size

48

In [21]:
# buffer onde o dado está salvo
b1d.data

## Manipulação de Arrays

In [23]:
b2d

array([[ 1,  3,  5],
       [ 7,  9, 10]])

In [24]:
# acessar um elemento
b2d[0]

array([1, 3, 5])

In [25]:
# acessar um elemento
b2d[0][1]

3

In [26]:
# acessar um elemento
b2d[0, 1]

3

In [53]:
b2d[1]

array([ 7,  9, 10])

In [28]:
# acessar um elemento
b2d[-1]

array([ 7,  9, 10])

In [54]:
b2d[-2]

array([1, 3, 5])

In [56]:
# b2d[-3]

In [29]:
# acessar um elemento
b2d[-1, -1]

10

In [32]:
for i in range(b2d.shape[0]):
  for j in range(b2d.shape[1]):
      print(b2d[i,j])

1
3
5
7
9
10


In [33]:
# slicing
# 0, 1
b2d[0][:2]

array([1, 3])

In [34]:
# slicing
b2d[0,:2]

array([1, 3])

In [35]:
# slicing
b2d[:2,:2]

array([[1, 3],
       [7, 9]])

In [37]:
#indexing
b2d[[0,1],[0,1]]

array([1, 9])

In [40]:
# indexing (get pairs)
b2d[[0,1],[0,1]]

array([1, 9])

In [36]:
# slicing + fancy indexing
b2d[[0,1],:2]

array([[1, 3],
       [7, 9]])